spring:
  application:
    name: "Banter Box"
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2h
    refreshTokenExpiration: 604800 # 7d
  profiles:
    active: dev

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers"