services:
  postgres:
    image: postgres:16
    container_name: banterbox-db
    environment:
      POSTGRES_DB: banterbox_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      internal:

volumes:
  pg_data:

networks:
  internal: